---
extends: default

rules:
  comments:
    min-spaces-from-content: 1
    require-starting-space: false
  comments-indentation: disable
  empty-lines:
    max-end: 1
  line-length: disable
  document-start: disable
  truthy:
    check-keys: false
  new-line-at-end-of-file: disable