name: Review the Checks output
description: Review the checks output and fail if any checks have failed

inputs:
  state_file_path:
    type: string
    description: "Path to Terraform State File"
    required: false
    default: "./terraform.tfstate"

runs:
  using: composite
  steps:
    - name: Validate Checks Output
      shell: pwsh
      run: >
        ${{ github.action_path }}/validate-checks-output.ps1
        -stateFilePath ${{ inputs.state_file_path }}
